### PR TITLE
(feat) server routes for getting and submitting repos

### PR DESCRIPTION
**Pull request by mrblueblue**
the app also automatically checkmarks repos the user has subscribed to

the server routes are app.get('/repo') and app.post('/repo')

### CODE REVIEW

**Comment by mrblueblue** [comment]
rebased

**Comment by rmagee88** [comment]
looks cool... I guess :smirk:

**Comment by mrblueblue** [comment]
yes, since this contains all of the changes in the previous PR

**Comment by rmagee88** [comment]
Cool- ship it!

-Rich

**Pull request closed without merging**
