### PR TITLE
(feat) Angular OAuth Passport-Github Integration

### PR DESCRIPTION
**Pull request by mrblueblue**
Changes are in the auth-test folder.

PR for code review purposes.

Eventually should be merged with server.js

### CODE REVIEW

**Comment by mrblueblue** [comment]
Modularized the auth into a middleware module.

See auth-middleware.js

**Comment by mrblueblue** [comment]
Latest push merges all my changes to server.js and client/

**Comment by koziscool** [comment]
looking now

**Comment by koziscool** [comment]
are you getting the x-origin error on index.html (in auth-test)?

**Comment by mrblueblue** [comment]
No, I'm not getting cross origin errors in my browser console

**Pull request closed without merging**
